### ISSUE TITLE
what was the issue?

### ISSUE THREAD

**Issue by ConfusedVorlon** [bigdondon/apple_developer_issue#1]
Curiosity here - what was the issue that caused the rejection / near-termination?

Glad this was sorted. It's terrible that Apple wields this power with so little apparent care.

**Comment by bigdondon** [comment]
At last,  I don't know.
She who made the call said I have submitted an app which had been submitted in another account previously, but obviously, this is not right. It's a brand new app in my account.
Let it go.

**Comment by csc-EricWu** [comment]
啥原因导致封号的？又怎样解决的？求分享
